import axios from "axios";
import { signLalamoveRequest } from "../utils/lalamoveSign.js";
import moment from "moment-timezone";
const SG_TZ = "Asia/Singapore";

const BASE = process.env.LALAMOVE_BASE_URL;
const API_KEY = process.env.LALAMOVE_API_KEY;
const MARKET = process.env.LALAMOVE_MARKET;

if (!BASE || !BASE.includes("lalamove.com")) {
  throw new Error("Invalid Lalamove BASE URL — check LALAMOVE_BASE_URL in .env");
};

console.log("🌍 LALAMOVE CONFIG →", {
  BASE,
  MARKET,
  KEY: API_KEY?.slice(0, 10) + "...",
});

async function signAndCall(path, method, bodyObj) {
  const bodyString = JSON.stringify(bodyObj); // ✅ FOR SIGNATURE
  const timestamp = Date.now().toString();

  const signature = signLalamoveRequest({
    method,
    path,
    body: bodyString, // ✅ string here
    timestamp,
  });

  console.log("🔐 SIGNATURE =", signature);

  console.log("📡 Lalamove CALL →", method, path);
  console.log("📡 Lalamove BODY →", bodyString);

  console.log(
    "POSTMAN_AUTH_HEADER =",
    `hmac ${API_KEY}:${timestamp}:${signature}`,
  );

  try {
    // 2. Instead of passing the object, pass the EXACT bodyString 
    // to ensure Axios doesn't re-stringify it with different spacing.
    const res = await axios.post(`${BASE}${path}`, bodyString, { 
      headers: {
        "Content-Type": "application/json",
        "Market": MARKET,
        "Authorization": `hmac ${API_KEY}:${timestamp}:${signature}`,
      },
    });

    console.log("✅ Lalamove RESPONSE →", res.data);
    return res;
  } catch (err) {
    console.log("❌ Lalamove ERROR STATUS →", err.response?.status);
    console.log("❌ Lalamove ERROR DATA →", err.response?.data);
    throw err;
  }
}

export async function createLalamoveOrder(order) {
  // 1. Basic Validations
  if (!order.pickupLocation?.lat || !order.deliveryAddress?.lat) {
    throw new Error("Coordinates missing");
  }

  /* =========================
     STEP 1 — QUOTATION
  ========================== */
  const quotePath = "/v3/quotations";
  const quoteBody = {
    data: {
      serviceType: "MOTORCYCLE",
      language: "en_SG",
      stops: [
        {
          address: order.pickupLocation.address,
          coordinates: {
            lat: order.pickupLocation.lat.toString(),
            lng: order.pickupLocation.lng.toString(),
          },
        },
        {
          address: order.deliveryAddress.addressText,
          coordinates: {
            lat: order.deliveryAddress.lat.toString(),
            lng: order.deliveryAddress.lng.toString(),
          },
        },
      ],
    },
  };

  console.log("📦 REQUESTING QUOTE...");
  const quoteRes = await signAndCall(quotePath, "POST", quoteBody);
  
  const quotationId = quoteRes.data.data.quotationId;
  // Get the IDs generated by Lalamove
  const stop0_id = quoteRes.data.data.stops[0].stopId || quoteRes.data.data.stops[0].id;
  const stop1_id = quoteRes.data.data.stops[1].stopId || quoteRes.data.data.stops[1].id;

  if (!quotationId) throw new Error("Quotation failed");

  /* =========================
     STEP 2 — CREATE ORDER
  ========================== */
  const orderPath = "/v3/orders";
  const orderBody = {
    data: {
      quotationId: quotationId,
      sender: {
        stopId: stop0_id, // Links back to the pickup stop
        name: "Bakery",
        phone: process.env.BAKERY_PHONE
      },
      recipients: [
        {
          stopId: stop1_id, // Links back to the delivery stop
          name: `${order.customer.firstName} ${order.customer.lastName}`,
          phone: order.customer.phone
        }
      ]
    }
  };

  console.log("🚚 PLACING ORDER...");
  const orderRes = await signAndCall(orderPath, "POST", orderBody);
  
  console.log("🎉 LALAMOVE ORDER SUCCESS:", orderRes.data.data.orderId);
  return orderRes.data;
}
export async function getLalamoveQuotation(pickup, drop) {
  const quotePath = "/v3/quotations";

  const body = {
    data: {
      serviceType: "MOTORCYCLE",
      language: "en_SG",
      stops: [
        {
          address: pickup.address,
          coordinates: {
            lat: pickup.lat.toString(),
            lng: pickup.lng.toString(),
          },
        },
        {
          address: drop.address,
          coordinates: {
            lat: drop.lat.toString(),
            lng: drop.lng.toString(),
          },
        },
      ],
    },
  };

  const res = await signAndCall(quotePath, "POST", body);
  return res.data.data;
}
